esphome:
  name: fan-controller-2

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret direct_wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true #fast connect enabled due to hidden ssid
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fan-Controller-2"
    password: !secret direct_wifi_password

captive_portal:

script:
  - id: button_press
    then:
    - switch.turn_on: bedside_fan_2
    - delay: 150ms
    - switch.turn_off: bedside_fan_2
    - delay: 150ms
    
switch:
  - platform: gpio
    pin:
      number: D7
      inverted: true
    name: "Bedside Fan 2"
    id: "bedside_fan_2"
    on_turn_on:
    - delay: 150ms
    - switch.turn_off: bedside_fan_2
  - platform: gpio
    pin: 
      number: D2
      inverted: true
    name: "Bedside Fan 2 Oscillation"
    id: "bedside_fan_2_oscillation"
    on_turn_on:
    - delay: 150ms
    - switch.turn_off: bedside_fan_2_oscillation
  - platform: gpio
    pin: 
      number: D1
      inverted: true
    name: "Bedside Fan 2 Power"
    id: "bedside_fan_2_power"
    on_turn_on:
    - delay: 150ms
    - switch.turn_off: bedside_fan_2_power