esphome:
  name: fan-controller

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret direct_wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true #fast connect enabled due to hidden ssid

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fan-Controller Fallback Hotspot"
    password: !secret direct_wifi_password

captive_portal:

switch:
  - platform: gpio
    pin:
      number: D1
      inverted: true
    name: "Bedside Fan"
    id: "bedside_fan"
    on_turn_on:
    - delay: 150ms
    - switch.turn_off: bedside_fan
  - platform: gpio
    pin: 
      number: D2
      inverted: true
    name: "Bedside Fan Oscillation"
    id: "bedside_fan_oscillation"
    on_turn_on:
    - delay: 150ms
    - switch.turn_off: bedside_fan_oscillation
  - platform: gpio
    pin: 
      number: D7
      inverted: true
    name: "Bedside Fan Power"
    id: "bedside_fan_power"
    on_turn_on:
    - delay: 150ms
    - switch.turn_off: bedside_fan_power