esphome:
  name: kip-waterbowl-2

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret direct_wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true #fast connect enabled due to hidden ssid

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kip-Waterbowl-2 Fallback Hotspot"
    password: !secret direct_wifi_password

captive_portal:
    
binary_sensor:
  - platform: gpio
    pin: 
      number: D1
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dog's Water Bowl2"